global using Xunit;
global using System;
global using System.Security;
global using System.Net.Mail;
global using System.Net;
global using OpenQA.Selenium.Chrome;
global using OpenQA.Selenium;
global using AventStack.ExtentReports.Reporter;
global using AventStack.ExtentReports;
global using System.IO;
global using Microsoft.Extensions.Configuration;
global using OpenQA.Selenium.Remote;
global using System.Collections.Generic;
global using System.Text;
global using System.Net.Http;
global using System.Net.Http.Headers;
global using System.Threading.Tasks;
global using OpenQA.Selenium.Support.UI;
global using OpenQA.Selenium.Firefox;
global using OpenQA.Selenium.Edge;
global using WebDriverManager;
global using WebDriverManager.DriverConfigs.Impl;
global using System.Threading;
global using System.IO.Enumeration;
global using NPOI.XSSF.UserModel;
global using UIAutomationTemplate.Utility;
global using System.Configuration;
global using Automation_Freshers.Helper;
global using SeleniumExtras.WaitHelpers;
global using UIAutomationTemplate.Services;
global using AventStack.ExtentReports.Model;
global using static NPOI.HSSF.Record.UnicodeString;
global using Org.BouncyCastle.Crypto.Tls;
global using OpenQA.Selenium.Interactions;
global using TechTalk.SpecFlow;
global using OpenQA.Selenium.DevTools;
global using OpenQA.Selenium.DevTools.V129.Network;
global using Network = OpenQA.Selenium.DevTools.V129.Network;
global using DevToolsSessionDomains = OpenQA.Selenium.DevTools.V129.DevToolsSessionDomains;

